Development
M3rcy139/DeliveryProject pull request #1
Opened 2024-12-12 19:45 UTC by M3rcy139

Изменил структуру проекта, переделал обработку ошибок, переделал тесты

2024-12-14 14:14 UTC, chaika-ds requested changes

2024-12-14 14:14 UTC, chaika-ds commented on DeliveryProject.Persistence/Configurations/AreaConfiguration.cs
>      public class AreaConfiguration : IEntityTypeConfiguration<AreaEntity>
Не нашел где используются конфигурации?

2024-12-14 14:14 UTC, chaika-ds commented on DeliveryProject.Persistence/PersistenceExtensions.cs
>      public static class PersistenceExtensions
Думаю, что сервис возвращать не нужно, сделай лучше метод void.

2024-12-14 14:14 UTC, chaika-ds commented on DeliveryProject.Persistence/Repositories/OrderRepository.cs
>      {
Нельзя ли _context.Orders.Add(orderEntity); сделать асинхронным? Может лучше в методе AddOrder возвращать или количество entry или данные по entity?

2024-12-14 14:29 UTC, chaika-ds requested changes

2024-12-14 14:29 UTC, chaika-ds commented on DeliveryProject/Program.cs
> +
Не читается текст в логгерах, подкорректируй его формат

2024-12-14 14:29 UTC, chaika-ds commented on DeliveryProject.Tests/OrderControllerTests.cs
> +        _orderServiceMock.Setup(repo => repo.GetAllOrders()).ThrowsAsync(new ArgumentException("������ �� �������"));
Исправить формат текста в ошибке

2024-12-14 14:29 UTC, chaika-ds commented on DeliveryProject.Tests/OrderControllerTests.cs
>      public async Task FilterOrders_ShouldReturnOk_WhenOrdersExist()
Тест падает с ошибкой 
Message: 
Expected response.StatusCode to be HttpStatusCode.NotFound {value: 404}, but found HttpStatusCode.InternalServerError {value: 500}.

  Stack Trace: 
XUnit2TestFramework.Throw(String message)
TestFrameworkProvider.Throw(String message)
DefaultAssertionStrategy.HandleFailure(String message)
AssertionScope.FailWith(Func`1 failReasonFunc)
AssertionScope.FailWith(Func`1 failReasonFunc)
AssertionScope.FailWith(String message, Object[] args)
EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
OrderControllerTests.FilterOrders_ShouldReturnBadRequest_WhenNoOrdersExist() line 71
--- End of stack trace from previous location ---

2024-12-18 18:14 UTC, Vadya0994 requested changes

2024-12-20 09:42 UTC, M3rcy139 commented on DeliveryProject.API/Controllers/OrderController.cs
> +        [HttpPost("add-order")]
Поменял нейминг на Order/Add

2024-12-20 09:43 UTC, M3rcy139 commented on DeliveryProject.API/Controllers/OrderController.cs
> +        [HttpGet("filter-orders")]
Поменял нейминг на Orders/Filter

2024-12-20 09:46 UTC, M3rcy139 commented on DeliveryProject.API/Controllers/OrderController.cs
> +            catch (ValidationException ex)
Перенес обработку ValidationException в ExceptionHandlingMiddleware
Добавил метод HandleExceptionAsync в класс ExceptionHandlingMiddleware и метод FullMessage разместил в статическом классе ExceptionExtensions, который находится в том же файле, что и ExceptionHandlingMiddleware

2024-12-20 09:47 UTC, M3rcy139 commented on DeliveryProject.API/Controllers/OrderController.cs
> +        [HttpGet("get-all-orders")]
Поменял нейминг на Orders/GetAll

2024-12-20 09:47 UTC, M3rcy139 commented on DeliveryProject.API/Middleware/ExceptionHandlingMiddleware.cs
> +            catch (ArgumentException ex)
Добавил ValidationException и расширил обработку ошибок

2024-12-20 09:48 UTC, M3rcy139 commented on DeliveryProject.Application/ApplicationExtensions.cs
> +            services.AddScoped<IValidator<Order>, AddOrderValidator>();
Сделал валидацию Singleton

2024-12-20 09:49 UTC, M3rcy139 commented on DeliveryProject.Application/ApplicationExtensions.cs
>          public static IServiceCollection AddApplication(this IServiceCollection services
Перенес конфигурацию сервисов в папку ServiceCollection в главный проект с точкой входа

2024-12-20 09:50 UTC, M3rcy139 commented on DeliveryProject.Persistence/PersistenceExtensions.cs
>      public static class PersistenceExtensions
Перенес конфигурацию сервисов в папку ServiceCollection в главный проект с точкой входа, сделал метод конфигурации void

2024-12-20 09:52 UTC, M3rcy139 commented on DeliveryProject.Application/Dto/AddOrderRequest.cs
>      public record AddOrderRequest
Изменил record на class и поля поменял на свойства

2024-12-20 09:54 UTC, M3rcy139 commented on DeliveryProject.Application/Services/OrderService.cs
> +            var validationResult = await _addOrderValidator.ValidateAsync(order);
В проекте .Bussiness создал папку Extensions и разместил там ValidatorExtensions, в котором написал метод
public static async Task<(bool IsValid, List<ValidationFailure> Errors)> TryValidateAsync<T>(
    this IValidator<T> validator, T instance)
{
    var validationResult = await validator.ValidateAsync(instance);
    return (validationResult.IsValid, validationResult.Errors);
}
В OrderService вынес валидацию в конструкцию TryValidateAsync

2024-12-20 09:55 UTC, M3rcy139 commented on DeliveryProject.Application/Services/OrderService.cs
> +                var errorMessages = validationResult.Errors
Использовал параметр в TryValidateAsync:
var (isValid, errors) = await _addOrderValidator.TryValidateAsync(order);

if (!isValid)
{
    var errorMessages = errors.Select(e => e.ErrorMessage).ToList();
    throw new ValidationException("Ошибка валидации", errors);
}

2024-12-20 09:57 UTC, M3rcy139 commented on DeliveryProject.Application/Services/OrderService.cs
> +            await _orderRepository.AddOrder(order);
Возвращаю результат метода в репозитории:
var result = await _orderRepository.AddOrder(orderEntity);

_logger.LogInformation($"Добавлен заказ с ID: {order.Id}");

return result;
В контроллере использую для отображения количества добавленных строк в таблице заказов

2024-12-20 09:59 UTC, M3rcy139 commented on DeliveryProject.Application/Services/OrderService.cs
> +            if (areaId <= 0)
Добавил следующий класс в папку Attributes в сборке .API:
public class GreaterThanZeroAttribute : ValidationAttribute
{
    protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
    {
        if (value is int intValue && intValue > 0)
        {
            return ValidationResult.Success;
        }

        return new ValidationResult("Введенное значение должно быть больше нуля.");
    }
}
Сейчас не используется, так как контроллер теперь принимает имя региона, а не Id

2024-12-20 10:01 UTC, M3rcy139 commented on DeliveryProject.Application/Validation/AddOrderValidator.cs
> +    public class AddOrderValidator : AbstractValidator<Order>
Переименовал в OrderValidator, раместил в папке Middleware в cборке .API

2024-12-20 10:02 UTC, M3rcy139 commented on DeliveryProject.Persistence/Configurations/AreaConfiguration.cs
>      public class AreaConfiguration : IEntityTypeConfiguration<AreaEntity>
Добавил в классе DeliveryDbContext метод:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.ApplyConfigurationsFromAssembly(typeof(DeliveryDbContext).Assembly);
}
```
Теперь конфигурации используются

2024-12-20 10:03 UTC, M3rcy139 commented on DeliveryProject.Persistence/Repositories/OrderRepository.cs
>      {
Сделал асинхронным

2024-12-20 10:04 UTC, M3rcy139 commented on DeliveryProject.Tests/OrderControllerTests.cs
>      public async Task FilterOrders_ShouldReturnOk_WhenOrdersExist()
Исправил работу тестов, теперь все проходят корректно

2024-12-20 10:04 UTC, M3rcy139 commented on DeliveryProject.Persistence/Migrations/20241023132011_initial.cs
> +namespace DeliveryProject.Access.Migrations
Исправил namespace, где было необходимо

2024-12-20 10:05 UTC, M3rcy139 commented on DeliveryProject.Persistence/Migrations/20241023132011_initial.cs
> +namespace DeliveryProject.Access.Migrations
Вынес миграции в сборку .Migrations

2024-12-20 10:06 UTC, M3rcy139 commented on DeliveryProject.Application/Validation/AddOrderValidator.cs
> +    public class AddOrderValidator : AbstractValidator<Order>
Переименовал в OrderValidator, раместил в папке Middleware в cборке .API

2024-12-20 10:07 UTC, M3rcy139 commented on DeliveryProject.Core/Interfaces/Repositories/IOrderRepository.cs
>      public interface IOrderRepository
Перенес интерфейсы в сборку .DataAccess, где находятся репозитории. Классы реализации репозиториев не отмечал Internal, так как приходится добавлять их в контейнеры в другой сборке

2024-12-20 10:08 UTC, M3rcy139 commented on DeliveryProject.Core/Interfaces/Services/IOrderService.cs
> +    public interface IOrderService
Вынес интерфейсы сервисов в новую сборку .BussinessContract

2024-12-20 10:08 UTC, M3rcy139 commented on DeliveryProject.Application/Dto/AddOrderRequest.cs
>      public record AddOrderRequest
Перенес Dto в папку Dto в сборку .API

2024-12-20 10:09 UTC, M3rcy139 commented on DeliveryProject.Application/DeliveryProject.Application.csproj
>      <PackageReference Include="FluentValidation" Version="11.10.0" />
Переименовал в Bussiness

2024-12-20 10:11 UTC, M3rcy139 commented on DeliveryProject.API/Middleware/ExceptionHandlingMiddleware.cs
> +            catch (ArgumentException ex)
Добавил папку Exceptions и в ней создал класс кастомного исключения BussinessArgumentException, добавил его обработку в ExceptionHandlingMiddleware

2024-12-20 10:14 UTC, M3rcy139 commented on DeliveryProject/Program.cs
> +    services.AddSwaggerGen();
Перенес конфигурацию и подключение middleware в сборку с точкой входа

2024-12-20 10:15 UTC, M3rcy139 commented on DeliveryProject.API/DeliveryProject.API.csproj
> +    <ProjectReference Include="..\DeliveryProject.Application\DeliveryProject.Application.csproj" />
Сделал

2024-12-20 10:27 UTC, M3rcy139 commented on DeliveryProject/Program.cs
> +    services.AddSwaggerGen();
Конфигурация сервисов в папке ServiceCollection:
```
public static void ConfigureServices(this IServiceCollection services, IConfiguration configuration)
{
    services.AddRouting();
    services.AddControllers();
    services.AddEndpointsApiExplorer();
    services.AddSwaggerGen();
    
    services.AddScoped<IOrderService, OrderService>();
    services.AddSingleton<IValidator<Order>, OrderValidator>();
    
    services.AddDbContext<DeliveryDbContext>(options =>
    {
        options.UseNpgsql(configuration.GetConnectionString(nameof(DeliveryDbContext)),
            b => b.MigrationsAssembly("DeliveryProject.Migrations"));
    });

    services.AddScoped<IOrderRepository, OrderRepository>();

    services.AddAutoMapper(typeof(DataBaseMappings));

    services.AddFluentValidationAutoValidation();
    services.AddFluentValidationClientsideAdapters();
    services.AddValidatorsFromAssemblyContaining<OrderValidator>();
}
```
Конфигурация middleware в отдельном классе MiddlewareConfiguration

2024-12-20 11:43 UTC, M3rcy139 commented on DeliveryProject.Repositories/DeliveryProject.Repositories.csproj
> +  <PropertyGroup>
Сделал

2024-12-20 11:43 UTC, M3rcy139 commented on DeliveryProject.Repositories/OrderRepository.cs
> +            if (region == null)
Перенес все проверки в слой с сервисами

2024-12-20 11:44 UTC, M3rcy139 commented on DeliveryProject.Repositories/OrderRepository.cs
>              return _mapper.Map<List<Order>>(orders);
Маппинг также перенес в сервисы в бизнес слое

2024-12-23 07:46 UTC, M3rcy139 commented on DeliveryProject.Core/Interfaces/Services/IOrderService.cs
> +    public interface IOrderService
Перенес интерфейсы сервисов в сборку, где лежат сервисы (.Bussiness)

2024-12-26 10:09 UTC, chaika-ds requested changes

2024-12-26 12:48 UTC, M3rcy139 commented on DeliveryProject.API/Dto/AddOrderRequest.cs
> +        public int regionId { get; set; }
Сделал

2024-12-27 10:22 UTC, M3rcy139 commented on DeliveryProject.API/Dto/AddOrderRequest.cs
> +        public int regionId { get; set; }
Сделал

2024-12-27 10:23 UTC, M3rcy139 commented on DeliveryProject.API/Middleware/ExceptionHandlingMiddleware.cs
> +    public static class ExceptionExtensions
Разместил ExceptionExtensions в папке Extensions в сборке .API

2024-12-27 10:24 UTC, M3rcy139 commented on DeliveryProject/MiddlewareConfiguration.cs
> +            app.UseRouting();
```
public static IApplicationBuilder ConfigureMiddleware(this IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseSwagger();
        app.UseSwaggerUI();
    }
    else
    {
        app.UseExceptionHandler("/error");
        app.UseHsts();
    }

    app.UseMiddleware<ExceptionHandlingMiddleware>();
    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();
    });

    app.UseHttpsRedirection();

    return app;
}
```
Вынес это в расширение MiddlewareConfiguration

2024-12-27 10:25 UTC, M3rcy139 commented on DeliveryProject/ServiceCollection/ServiceConfiguration.cs
> +            services.AddFluentValidationAutoValidation();
Вынес валидацию в класс FluentValidationConfiguration

2024-12-27 10:25 UTC, M3rcy139 commented on DeliveryProject/ServiceCollection/ServiceConfiguration.cs
> +            services.AddScoped<IOrderService, OrderService>();
Контейнеры с сервисами и репозиториями вынес в класс DependencyInjectionConfiguration

2024-12-28 12:50 UTC, chaika-ds commented on DeliveryProject.API/Middleware/ExceptionHandlingMiddleware.cs
> +    public static class ExceptionExtensions
Ок

2024-12-28 13:29 UTC, chaika-ds commented on DeliveryProject.API/Middleware/OrderValidator.cs
> +        public OrderValidator()
Ок

2024-12-28 14:14 UTC, chaika-ds approved these changes
Изменения в PR все проведены, делаем approve и переходим к следующему модулю.

2024-12-28 14:14 UTC, chaika-ds commented on DeliveryProject/Program.cs
> +    services.AddSwaggerGen();
Конфигурация разнесена отлично и читаемо
Ок

2024-12-28 14:16 UTC, chaika-ds commented on DeliveryProject.API/Controllers/OrderController.cs
> +            catch (ValidationException ex)
Ок

2024-12-28 14:34 UTC, chaika-ds commented on DeliveryProject.Tests/OrderControllerTests.cs
>      public async Task FilterOrders_ShouldReturnOk_WhenOrdersExist()
ок

2024-12-28 14:36 UTC, chaika-ds commented on DeliveryProject.Core/Interfaces/Repositories/IOrderRepository.cs
>      public interface IOrderRepository
Ок

2024-12-28 14:41 UTC, chaika-ds commented on DeliveryProject.Repositories/OrderRepository.cs
> +            if (region == null)
Ок

2024-12-28 14:42 UTC, chaika-ds commented on DeliveryProject.Repositories/OrderRepository.cs
>              return _mapper.Map<List<Order>>(orders);
Доработаем в следующем модуле  https://github.com/M3rcy139/DeliveryProject/issues/7

Ок

2024-12-28 14:43 UTC, chaika-ds commented on DeliveryProject.API/Dto/AddOrderRequest.cs
> +        public int regionId { get; set; }
Ок

2024-12-28 14:45 UTC, chaika-ds commented on DeliveryProject.Core/Exceptions/BussinessArgumentException.cs
> +        public BussinessArgumentException(string message)
Ок

2024-12-28 14:45 UTC, chaika-ds commented on DeliveryProject/ServiceCollection/ServiceConfiguration.cs
> +            services.AddFluentValidationAutoValidation();
Ок

2024-12-28 14:45 UTC, chaika-ds commented on DeliveryProject/MiddlewareConfiguration.cs
> +            app.UseRouting();
Ок

2024-12-28 14:46 UTC, chaika-ds commented on DeliveryProject/ServiceCollection/ServiceConfiguration.cs
> +            services.AddScoped<IOrderService, OrderService>();
Ок

2024-12-28 15:24 UTC, Vadya0994 approved these changes

2024-12-28 19:33 UTC, merged