Adjusted error handling, validation, added sorting
M3rcy139/DeliveryProject pull request #16
Opened 2024-12-30 15:57 UTC by M3rcy139

2025-01-12 12:10 UTC, chaika-ds requested changes

2025-01-12 12:10 UTC, chaika-ds commented on DeliveryProject.Bussiness/Services/OrderService.cs
> +            "ORDERS_NOT_FOUND_IN_REGION");
Сделать класс с константами описания errorCode и подставлять поле с константами вместа строк

2025-01-12 12:10 UTC, chaika-ds commented on DeliveryProject.Bussiness/Services/OrderService.cs
> +            if (sortBy != null)
Ванести if/else в отдельный метод сортировки.

2025-01-12 12:10 UTC, chaika-ds commented on DeliveryProject.Bussiness/Services/OrderService.cs
> +        private Func<IQueryable<OrderEntity>, IOrderedQueryable<OrderEntity>>? GetOrdersByDelegate(SortField? sortBy, bool descending)
Вынести в отдельный класс, предназначенный для сортировки

2025-01-12 12:10 UTC, chaika-ds commented on DeliveryProject.Bussiness/Services/OrderService.cs
> -        public OrderService(IOrderRepository orderRepository, ILogger<OrderService> logger
Много параметров передается в конструктор, одна из причин оптимизировать класс. Это значит вынести места, еде используются например валидатор и репозиторий и связать их через агрегацию или наследование.

2025-01-12 12:10 UTC, chaika-ds commented on DeliveryProject.DataAccess/Repositories/OrderRepository.cs
> +        public async Task<List<OrderEntity>> GetAllOrdersImmediate()
Можно упростить функции общения с репозиторием через оператор =>

2025-01-12 12:10 UTC, chaika-ds commented on DeliveryProject/ServiceCollection/MiddlewareConfiguration.cs
> +            app.UseMiddleware<ValidationMiddleware>();
Можно объединить все собственные middleware в одном классе.

2025-01-12 13:02 UTC, chaika-ds requested changes

2025-01-12 13:02 UTC, chaika-ds commented on DeliveryProject/Program.cs
> +    services.AddControllers()
Вынести в расширение AddControllers и можно объединить в одном классе со сваггером

2025-01-12 13:02 UTC, chaika-ds commented on DeliveryProject/Program.cs
>      services.AddControllers();
Повторение AddControllers

2025-01-12 13:02 UTC, chaika-ds commented on DeliveryProject/ServiceCollection/DependencyInjectionConfiguration.cs
> +            services.AddScoped<IDeliveryPersonRepository, DeliveryPersonRepository>();
Отдельить имплементацию сервисов и репозитория по разным методам

2025-01-14 17:07 UTC, M3rcy139 commented on DeliveryProject.API/Extensions/CustomProblemDetails.cs
> +    public class CustomProblemDetails : ProblemDetails
Перенес

2025-01-14 17:08 UTC, M3rcy139 commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
> +                    var validationResult = await orderValidator.TryValidateAsync(order);
Теперь TryValidateAsync возвращает bool и выбрасывают ошибку для обработки на более высоких уровнях, если валидации не прошла

2025-01-14 17:08 UTC, M3rcy139 commented on DeliveryProject.API/Extensions/ValidationResult.cs
> +    public class ValidationResult<T>
Перенес в папку Models в сборке .API

2025-01-14 17:09 UTC, M3rcy139 commented on DeliveryProject.Bussiness/Enums/SortField.cs
> +    public enum SortField
Сделал

2025-01-14 17:10 UTC, M3rcy139 commented on DeliveryProject.Bussiness/Services/OrderService.cs
>              var orderEntity = new OrderEntity()
Перенес делегат и проверку в класс OrderSortingHelper в папку Helpers в сборке .Bussiness

2025-01-14 17:11 UTC, M3rcy139 commented on DeliveryProject.Bussiness/Services/OrderService.cs
> +            "ORDERS_NOT_FOUND_IN_REGION");
Создал папку Constants в .Core и там класс ErrorCodes

2025-01-14 17:15 UTC, M3rcy139 commented on DeliveryProject.Bussiness/Services/OrderService.cs
> -        public OrderService(IOrderRepository orderRepository, ILogger<OrderService> logger
Создал класс OrderRepositoryFacade в папке Facades в .Bussiness и туда вынес использование репозиториев. Сам класс OrderService использует только этот фасад

2025-01-14 17:16 UTC, M3rcy139 commented on DeliveryProject.DataAccess/Repositories/OrderRepository.cs
> +        public async Task<List<OrderEntity>> GetAllOrdersImmediate()
Сделал

2025-01-14 17:16 UTC, M3rcy139 commented on DeliveryProject/ServiceCollection/MiddlewareConfiguration.cs
> +            app.UseMiddleware<ValidationMiddleware>();
Сделал

2025-01-14 17:16 UTC, M3rcy139 commented on DeliveryProject.API/Attributes/GreaterThanZeroAttribute.cs
>                  return ValidationResult.Success;
Удалил атрибут

2025-01-14 17:17 UTC, M3rcy139 commented on DeliveryProject.API/Attributes/GreaterThanZeroAttribute.cs
> +            return new ValidationResult("The entered value must be greater than zero.");
Перенес в класс ErrorMessages в папке Constants

2025-01-14 17:17 UTC, M3rcy139 commented on DeliveryProject.API/Controllers/OrderController.cs
> +                message = "The order was successfully added."
Сделал класс InfoMessages в папке Constants

2025-01-14 17:19 UTC, M3rcy139 commented on DeliveryProject.Bussiness/Mappings/DataBaseMappings.cs
> +            CreateMap<ParticipantEntity, Participant>();
Переименовал на BaseUnit и BaseUnitEntity

2025-01-14 17:20 UTC, M3rcy139 commented on DeliveryProject.Core/Models/FilteredOrder.cs
>      public class FilteredOrder
Он используется для сохранения результатов фильтрации, такое условие было в изначальном ТЗ

2025-01-14 17:20 UTC, M3rcy139 commented on DeliveryProject/Program.cs
> +    services.AddControllers()
Сделал

2025-01-14 17:21 UTC, M3rcy139 commented on DeliveryProject/Program.cs
>      services.AddControllers();
Убрал повторение

2025-01-14 17:21 UTC, M3rcy139 commented on DeliveryProject/ServiceCollection/DependencyInjectionConfiguration.cs
> +            services.AddScoped<IDeliveryPersonRepository, DeliveryPersonRepository>();
Сделал

2025-01-16 23:31 UTC, chaika-ds requested changes

2025-01-16 23:31 UTC, chaika-ds commented on DeliveryProject.Core/Constants/ErrorCodes.cs
> +        public static class Order
Здесь достаточно все объединить в одном классе, кодов не так много и в строках один за другим они легко читаются.
Соответственно переименовать например NotFound в RegionNotFound

2025-01-16 23:31 UTC, chaika-ds commented on DeliveryProject.Core/Constants/ErrorMessages.cs
> +    {
Здесь можно сделать папку ErrorMessages и разнести отдельно классы сообщений о валидации и об ошибках, а остальное объединитьв одном классе например OrderErrorMessages

2025-01-16 23:31 UTC, chaika-ds commented on DeliveryProject.Core/Constants/InfoMessages.cs
> +    {
Сделать каки с ErrorMessages, разнести по классам в одной папке, или просто объединить классы в одном, здесь пока не очень много констант.

2025-01-16 23:31 UTC, chaika-ds commented on DeliveryProject.DataAccess/Repositories/DeliveryPersonRepository.cs
>          public async Task<DeliveryPersonEntity?> GetAvailableDeliveryPersonAsync(DateTime deliveryTime)
Асинхронный метод без асинхроного исполнения

2025-01-16 23:32 UTC, chaika-ds commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
> +                    var body = await new StreamReader(context.Request.Body).ReadToEndAsync();
+

2025-01-16 23:32 UTC, chaika-ds commented on DeliveryProject.API/Extensions/CustomProblemDetails.cs
> +    public class CustomProblemDetails : ProblemDetails
Ok

2025-01-16 23:33 UTC, chaika-ds commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
> +                    var validationResult = await orderValidator.TryValidateAsync(order);
Добавил уточнение для доработки в последнем коммите

2025-01-16 23:35 UTC, chaika-ds commented on DeliveryProject.API/Extensions/ValidationResult.cs
> +    public class ValidationResult<T>
Ок.
Предлагаю разнести сборку Апи, и пристроить эту модель в Core. Это на следующий модуль.

2025-01-16 23:35 UTC, chaika-ds commented on DeliveryProject.Bussiness/Enums/SortField.cs
> +    public enum SortField
Ок

2025-01-16 23:38 UTC, chaika-ds commented on DeliveryProject.Bussiness/Services/OrderService.cs
> +            if (sortBy != null)
По поводу вынести if/else в отдельный метод сортировки, имел ввиду вынести все if, см мой предыдущий коммент.

2025-01-17 06:55 UTC, chaika-ds commented on DeliveryProject.Bussiness/Services/OrderService.cs
> +            "ORDERS_NOT_FOUND_IN_REGION");
Ок
Доработка класса в комментариях к коммиту.

2025-01-17 06:56 UTC, chaika-ds commented on DeliveryProject.Bussiness/Services/OrderService.cs
> +        private Func<IQueryable<OrderEntity>, IOrderedQueryable<OrderEntity>>? GetOrdersByDelegate(SortField? sortBy, bool descending)
Ок

2025-01-17 06:56 UTC, chaika-ds commented on DeliveryProject.Bussiness/Services/OrderService.cs
> -        public OrderService(IOrderRepository orderRepository, ILogger<OrderService> logger
Ок
Предлагаю доработать в виде медиатора

2025-01-17 06:57 UTC, chaika-ds commented on DeliveryProject.DataAccess/Repositories/OrderRepository.cs
> +        public async Task<List<OrderEntity>> GetAllOrdersImmediate()
Ок

2025-01-17 06:57 UTC, chaika-ds commented on DeliveryProject/ServiceCollection/MiddlewareConfiguration.cs
> +            app.UseMiddleware<ValidationMiddleware>();
Ок

2025-01-17 07:00 UTC, chaika-ds commented on DeliveryProject.API/Attributes/GreaterThanZeroAttribute.cs
>                  return ValidationResult.Success;
Ок

2025-01-17 07:00 UTC, chaika-ds commented on DeliveryProject.API/Attributes/GreaterThanZeroAttribute.cs
> +            return new ValidationResult("The entered value must be greater than zero.");
Ок
Доработать по замечаниям в 4 коммите

2025-01-17 07:01 UTC, chaika-ds commented on DeliveryProject.API/Middleware/ExceptionHandlingMiddleware.cs
> +                _logger.LogError($"Business logical exception: {ex.Message}");
Ок

2025-01-17 07:02 UTC, chaika-ds commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
> +                        throw new ValidationException("An empty Order object.");
Ок

2025-01-17 07:02 UTC, chaika-ds commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
> +                    var problemDetails = new CustomProblemDetails
Ок

2025-01-17 07:02 UTC, chaika-ds commented on DeliveryProject.API/Validation/OrderValidator.cs
> +                .GreaterThan(0).WithMessage("The RegionId must be greater than zero.");
Ок

2025-01-17 07:06 UTC, chaika-ds commented on DeliveryProject.Bussiness/Mappings/DataBaseMappings.cs
> +            CreateMap<ParticipantEntity, Participant>();
Ок

2025-01-17 07:10 UTC, chaika-ds commented on DeliveryProject.Tests/OrderControllerTests.cs
>          _orderServiceMock
Ок
В следующих модулях

2025-01-17 07:11 UTC, chaika-ds commented on DeliveryProject.Tests/OrderControllerTests.cs
>              RegionId = 0,
Ок
В следующих модулях

2025-01-17 07:16 UTC, chaika-ds commented on DeliveryProject.Tests/OrderControllerTests.cs
> +        responseContent.Detail.Should().NotBeNullOrEmpty();
Ок
В следующих модулях

2025-01-17 07:16 UTC, chaika-ds commented on DeliveryProject/Program.cs
> +    services.AddControllers()
Ок

2025-01-17 07:16 UTC, chaika-ds commented on DeliveryProject/Program.cs
>      services.AddControllers();
Ок

2025-01-18 14:41 UTC, M3rcy139 commented on DeliveryProject.DataAccess/Repositories/DeliveryPersonRepository.cs
>          public async Task<DeliveryPersonEntity?> GetAvailableDeliveryPersonAsync(DateTime deliveryTime)
Сделал асинхронное исполнение

2025-01-18 14:42 UTC, M3rcy139 commented on DeliveryProject.Core/Constants/InfoMessages.cs
> +    {
Объединил в одной папке

2025-01-18 14:42 UTC, M3rcy139 commented on DeliveryProject.Core/Constants/ErrorMessages.cs
> +    {
Сделал папку ErrorMessages и создал там два класса ErrorMessages и ValidationErrorMessages

2025-01-18 14:43 UTC, M3rcy139 commented on DeliveryProject.Core/Constants/ErrorCodes.cs
> +        public static class Order
Объединил в одном классе

2025-01-18 14:43 UTC, M3rcy139 commented on DeliveryProject.Bussiness/Helpers/OrderSortingHelper.cs
> +        public static void ValidateOrders(List<OrderEntity> orders)
Сделал

2025-01-18 14:43 UTC, M3rcy139 commented on DeliveryProject.Bussiness/Helpers/OrderSortingHelper.cs
> +        public static Func<List<OrderEntity>, List<OrderEntity>>? GetSortDelegate(OrderSortField? sortBy, bool descending)
Сделал

2025-01-18 14:44 UTC, M3rcy139 commented on DeliveryProject.Bussiness/Facades/OrderRepositoryFacade.cs
> +    public class OrderRepositoryFacade
Переделал в RepositoryMediator

2025-01-18 14:44 UTC, M3rcy139 commented on DeliveryProject.API/Extensions/ValidatorExtensions.cs
>              var validationResult = await validator.ValidateAsync(instance);
Сделал

2025-01-18 14:44 UTC, M3rcy139 commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
>                      if (order == null)
Вынес в TryValidate

2025-01-18 14:44 UTC, M3rcy139 commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
>                      var order = JsonSerializer.Deserialize<Order>(body, new JsonSerializerOptions
Сделал

2025-01-20 10:18 UTC, chaika-ds commented on DeliveryProject.DataAccess/Repositories/DeliveryPersonRepository.cs
>          public async Task<DeliveryPersonEntity?> GetAvailableDeliveryPersonAsync(DateTime deliveryTime)
Ok

2025-01-20 10:21 UTC, chaika-ds commented on DeliveryProject.Core/Constants/InfoMessages.cs
> +    {
OK

2025-01-20 10:22 UTC, chaika-ds commented on DeliveryProject.Core/Constants/ErrorCodes.cs
> +        public static class Order
Ok

2025-01-20 14:13 UTC, chaika-ds commented on DeliveryProject.Bussiness/Helpers/OrderSortingHelper.cs
> +        public static void ValidateOrders(List<OrderEntity> orders)
Доработать по комментам в последнем пр.

2025-01-20 14:57 UTC, chaika-ds commented on DeliveryProject.Bussiness/Helpers/OrderSortingHelper.cs
> +        public static Func<List<OrderEntity>, List<OrderEntity>>? GetSortDelegate(OrderSortField? sortBy, bool descending)
Ok

2025-01-20 16:59 UTC, chaika-ds commented on DeliveryProject.API/Extensions/ValidatorExtensions.cs
>              var validationResult = await validator.ValidateAsync(instance);
Доработать.
Здесь возвращать false, чтобы соблюдать правильность Try конструкции
if (!validationResult.IsValid)
{
    throw new ValidationException(string.Format(ValidationErrorMessages.ValidationFailed, 
        validationResult.Errors), validationResult.Errors);
}

Вметоде InvokeAsync:
Здесь универсализировать один ValidationErrorMessages, чтобы он прямо указывал на метод где упал, а уже внутри мтода можно будет разбираться в присчинах не прохождения валидации. С одной стороны делать в свои исключения это правильно, но тут тоже не нужно излишне перецсложнять. 
if (!isValid)
{
    throw new ValidationException(ValidationErrorMessages.EmptyOrderObject);
}

Здесь можно использовать else

if (isValid)
{
    _logger.LogInformation(InfoMessages.ValidationSucceeded);
}

2025-01-20 17:00 UTC, chaika-ds commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
>                      if (order == null)
Ok

2025-01-21 09:24 UTC, chaika-ds commented on DeliveryProject.Core/Extensions/JsonExtensions.cs
> +        public static T DeserializeValue<T>(this string json, JsonSerializerOptions options = null)
Добавь здесь JsonSerializerOptions?,  иначе у меня выдает ошибку что options никогда не могут быть null

2025-01-21 09:24 UTC, chaika-ds commented on DeliveryProject.Core/Extensions/JsonExtensions.cs
> +                throw new ArgumentException("JSON строка не может быть пустой или null.", nameof(json));
Ну вот исправили и снова, все сообщения об ошибках: на английский и в константы.

2025-01-21 09:24 UTC, chaika-ds commented on DeliveryProject.API/Middleware/ValidationMiddleware.cs
>                      var order = JsonSerializer.Deserialize<Order>(body, new JsonSerializerOptions
Ок

2025-01-21 09:28 UTC, chaika-ds commented on DeliveryProject.API/Attributes/GreaterThanZeroAttribute.cs
> +            return new ValidationResult("The entered value must be greater than zero.");
Ок

2025-01-21 09:28 UTC, chaika-ds commented on DeliveryProject.API/Controllers/OrderController.cs
> +                message = "The order was successfully added."
Ок

2025-01-21 11:31 UTC, chaika-ds approved these changes

2025-01-21 16:32 UTC, Vadya0994 approved these changes

2025-01-22 16:05 UTC, chaika-ds commented on DeliveryProject.Core/Extensions/JsonExtensions.cs
> +                throw new ArgumentException("JSON строка не может быть пустой или null.", nameof(json));
Ок

2025-01-22 16:05 UTC, chaika-ds commented on DeliveryProject.Core/Extensions/JsonExtensions.cs
> +        public static T DeserializeValue<T>(this string json, JsonSerializerOptions options = null)
Ок

2025-01-22 16:07 UTC, chaika-ds commented on DeliveryProject.Core/Extensions/CollectionExtensions.cs
> +        public static ICollection<T> IsNullOrEmpty<T>(this ICollection<T> source)
Ок

2025-01-22 20:35 UTC, merged